verbosity: debug
kubernetes:
  # kubeconfig: 
  namespace: kaniko-remote
builder:
  instanceId: lucas
  useDebugImage: False
  cpu: 1
  memory: 1G
  # additionalLabels:
  #   yes: hello
  # additionalAnnotations:
  #   why: not
auth:
  - url: eliiza.azurecr.io
    alwaysMount: False
    type: acr
    serviceAccount: False
    secretAsEnvVars: eliiza-azurecr-push-sp
    secretAsFile: False
    #TODO: mount this as /secrets (from kaniko docs, for gcp)
    token: False
  - url: gs://kaniko-bucket
    type: pod-only
    serviceAccount: False
    secretAsEnvVars: False
    secretAsFile: False
  - url: s3://kaniko-bucket
    serviceAccount: False
    secretAsEnvVars: False
    secretAsFile: False
  - url: https://myaccount.blob.core.windows.net/container
    serviceAccount: False
    secretAsEnvVars: False
    secretAsFile: False
