kubernetes:
  namespace: kaniko-remote
builder:
  name: lucas
  # keepPod: true
  # kanikoImage: gcr.io/kaniko-project/executor:debug
tags:
  prefix: eliiza.azurecr.io/lucas-dev
auth:
  - type: acr
    registry: eliiza.azurecr.io
    mount: always
    env:
    - fromSecret: eliiza-azurecr-push-sp