name: Build

env:
  DOTNET_VERSION: 6.0.x

on:
  push:
    branches:
    - main

jobs:
  build-linux-x64:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup dotnet
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore -r linux-x64
    - name: Test
      env:
        KUBECONFIG: ${{ secrets.KUBECONFIG }}
      run: |
        # echo $KUBECONFIG | base64 -d > .kube/config
        dotnet test --no-build --verbosity normal
    - name: Get version string
      id: version_step
      run: echo "::set-output name=version::$(dotnet run -r linux-x64 -- version)"
    - name: Publish linux-x64 binary
      run: dotnet publish -r linux-x64 -o dist
    - name: Archive build
      uses: actions/upload-artifact@v3
      with:
        name: kaniko-remote-${{ steps.version_step.outputs.version }}-linux-x64
        path: dist/*