name: Build
on:
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    environment: lucas_env
    strategy:
      matrix:
       include:
        # - python-version: 3.6
        #   python-version-str: "py36"
        # - python-version: 3.7
        #   python-version-str: "py37"
        # - python-version: 3.8
        #   python-version-str: "py38"
        - python-version: 3.9
          python-version-str: "py39"
    steps:
      - uses: actions/checkout@v2
      - name: Set up ${{ matrix.python-version-str }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Run Black
        run: |
          python -m pip install black
          black --check --diff src tests
      - name: Install dependencies, for extras and tests too
        run: |
          python -m pip install --upgrade pip
          pip install .[tests]
      - name: Test with pytest
        env:
          KUBECONFIG: ${{ secrets.KUBECONFIG }}
        run: |
          echo $KUBECONFIG | base64 -d > .kube/config
          pytest