name: Build
on:
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    environment: lucas_env
    steps:
      - uses: actions/checkout@v2
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
      - name: Test
        env:
          KUBECONFIG: ${{ secrets.KUBECONFIG }}
        run: |
          echo $KUBECONFIG | base64 -d > .kube/config
          dotnet test --no-build --verbosity normal
      - name: Build self-contained apps
        run: |
          dotnet publish -r linux-x64 -o dist
          mv dist/kaniko-remote dist/kaniko-remote.${{ GITHUB_SHA }}.linux-x64
          dotnet publish -r linux-musl-x64 -o dist
          mv dist/kaniko-remote dist/kaniko-remote.${{ GITHUB_SHA }}.linux-musl-x64
          dotnet publish -r linux-arm -o dist
          mv dist/kaniko-remote dist/kaniko-remote.${{ GITHUB_SHA }}.linux-arm
          dotnet publish -r linux-arm64 -o dist
          mv dist/kaniko-remote dist/kaniko-remote.${{ GITHUB_SHA }}.linux-arm64
          dotnet publish -r osx-x64 -o dist
          mv dist/kaniko-remote dist/kaniko-remote.${{ GITHUB_SHA }}.osx-x64
          dotnet publish -r osx-arm64 -o dist
          mv dist/kaniko-remote dist/kaniko-remote.${{ GITHUB_SHA }}.osx-arm64
      - name: Archive builds
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: |
            dist